name: php-fundamentals

services:

  webserver:
    container_name: webserver
    build:
      context: .
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    volumes:
      - ./:/var/www/html/app
    ports:
      - '80:80'